apiVersion: apps/v1
kind: Deployment
metadata:
  name: backuser
  labels:
    app: backuser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backuser
  template:
    metadata:
      labels:
        app: backuser
    spec:
      containers:
      - name: backuser
        image: vitorta/backuser:2
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: questcode
              key: NODE_ENV        
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: questcode
              key: MONGO_URI
        - name: SECRET_OR_KEY
          valueFrom:
            secretKeyRef:
              name: questcode
              key: SECRET_OR_KEY        
        ports:
        - containerPort: 3020