kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins
  labels:
    type: local
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: manual-for-jenkins
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-jenkins"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: devops
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: manual-for-jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi